"""M6 automated knowledge operations — control-plane orchestration store.

The operations package owns durable orchestration state (asset lifecycle, job
state machine, attempts, workers, event log). It is deliberately independent of
src.knowledge (M4/M5 canonical knowledge store).
"""

from .models import (
    OPERATIONS_SCHEMA_VERSION,
    OPERATIONS_POLICY_VERSION,
    OPERATIONS_USER_VERSION,
    DEFAULT_OPERATIONS_PATH,
    AssetLifecycleState,
    JobState,
    JobStage,
    PipelineRunStatus,
    TriggerType,
    TERMINAL_JOB_STATES,
    LEASE_HELD_JOB_STATES,
    VALID_CAPABILITIES,
    is_terminal_job_state,
    is_legal_asset_transition,
    is_legal_job_transition,
    normalize_identity_component,
    normalize_input_fingerprint,
    normalize_job_stage,
    normalize_capability,
    normalize_capabilities,
    compute_job_id,
    is_valid_job_id,
    utc_now_iso,
    parse_iso,
    format_iso,
    compute_backoff_seconds,
    compute_next_retry_at,
    new_lease_token,
    EnqueueResult,
    ClaimedJob,
    OperationsValidationResult,
)
from .store import (
    OperationsError,
    OperationsSchemaError,
    OperationsStateError,
    OperationsIntegrityError,
    StaleLeaseError,
    DEFAULT_MAX_ATTEMPTS,
    DEFAULT_LEASE_DURATION_SECONDS,
    DEFAULT_WORKER_STALE_THRESHOLD_SECONDS,
    create_operations_store,
    open_operations_store,
    register_asset,
    get_asset,
    get_asset_by_canonical_id,
    transition_asset_lifecycle,
    admin_requeue_asset_lifecycle,
    create_pipeline_run,
    complete_pipeline_run,
    get_pipeline_run,
    enqueue_job,
    get_job,
    list_jobs,
    list_pending_jobs,
    list_failed_jobs,
    transition_job_state,
    begin_attempt,
    finish_attempt,
    list_job_attempts,
    cancel_job,
    requeue_retryable_job,
    set_job_lease,
    clear_job_lease,
    register_worker,
    worker_heartbeat,
    list_workers,
    list_workers_with_status,
    claim_next_job,
    renew_job_lease,
    start_claimed_job,
    complete_job_success,
    complete_job_retryable_failure,
    complete_job_terminal_failure,
    find_active_claim,
    replay_started_job,
    replay_completed_job,
    recover_expired_leases,
    is_worker_stale,
    get_job_result,
    list_events,
    validate_operations_store,
)
from .worker import (
    RetryableJobError,
    TerminalJobError,
    HandlerResult,
    WorkerRunResult,
    WorkerRuntime,
    StageHandler,
)
from .stages import (
    STAGES_POLICY_VERSION,
    STAGE_EXECUTION_RESULT_SCHEMA_VERSION,
    STATUS_EXECUTED,
    STATUS_CACHE_HIT,
    ArtifactDescriptor,
    StageExecutionResult,
    is_valid_sha256,
    fingerprint_artifacts,
    stage_output_fingerprint,
    required_capabilities_for_stage,
    StageAdapter,
    DiscoverAdapter,
    ArchiveAdapter,
    MediaProcessAdapter,
    KnowledgeExtractAdapter,
    KnowledgeFinalizeAdapter,
    StoreIngestAdapter,
    build_stage_handler_registry,
    validate_stage_execution_result,
)
from .scheduler import (
    SCHEDULER_POLICY_VERSION,
    SCHEDULER_SCHEMA_VERSION,
    SchedulerCycleResult,
    PollSource,
    Scheduler,
    SchedulerError,
    discovery_control_fingerprint,
    poll_slot_fingerprint,
    epoch_seconds,
)
from .observability import (
    HEALTH_HEALTHY,
    HEALTH_RUNNING,
    HEALTH_WAITING_FOR_WORKER,
    HEALTH_WAITING_RETRY,
    HEALTH_SUCCEEDED,
    HEALTH_FAILED_TERMINAL,
    HEALTH_CANCELLED,
    HEALTH_STALLED,
    HEALTH_INVARIANT_ERROR,
    MANUAL_ATTENTION_HEALTH,
    AssetPipelineStatus,
    WorkerStatus,
    OperationsSummary,
    get_asset_pipeline_status,
    list_asset_pipeline_statuses,
    get_worker_status,
    list_worker_statuses,
    compute_operations_summary,
    get_asset_timeline,
)
from .admin import (
    ADMIN_POLICY_VERSION,
    RecoveryResult,
    AdminRetryResult,
    AdminCancelResult,
    run_recovery_pass,
    startup_recovery,
    admin_retry_job,
    admin_cancel_job,
    admin_requeue_asset,
)
from .transport import (
    TransportError,
    RemoteUnavailableError,
    WorkerOperationsTransport,
    LocalSQLiteWorkerTransport,
)
from .http_transport import (
    CONTROL_PLANE_API_VERSION,
    ERROR_CODE_AUTH_FAILED,
    ERROR_CODE_VALIDATION_ERROR,
    ERROR_CODE_NO_JOB,
    ERROR_CODE_STALE_LEASE,
    ERROR_CODE_CONFLICT,
    ERROR_CODE_NOT_FOUND,
    ERROR_CODE_SERVER_UNAVAILABLE,
    ERROR_CODE_INVARIANT_ERROR,
    ApiError,
    AuthenticationError,
    claimed_job_to_dict,
    claimed_job_from_dict,
    redact_job_payload,
    HttpWorkerTransport,
)

# M6-06/M6-07 entrypoint modules (windows_worker, control_plane) are imported
# lazily (PEP 562 __getattr__) so that `python -m src.operations.windows_worker`
# and `python -m src.operations.control_plane` do not trigger the runpy
# RuntimeWarning ("found in sys.modules after import of package ..."). The
# public API surface is preserved: `from src.operations import ...` still
# resolves the names below.

_CONTROL_PLANE_EXPORTS = frozenset(
    {
        "CONTROL_PLANE_CONFIG_VERSION",
        "CONTROL_PLANE_POLICY_VERSION",
        "WINDOWS_STAGE_ALLOWLIST",
        "NAS_STAGE_ALLOWLIST",
        "DEFAULT_AUTH_TOKEN_ENV",
        "ControlPlaneConfig",
        "ControlPlaneService",
        "run_control_plane",
        "build_nas_local_handlers",
    }
)

_WINDOWS_WORKER_EXPORTS = frozenset(
    {
        "WORKER_HOST_CONFIG_VERSION",
        "WORKER_PREFLIGHT_RESULT_VERSION",
        "WORKER_HOST_POLICY_VERSION",
        "WINDOWS_PC_TARGET_CAPABILITIES",
        "CONTROL_PLANE_TRANSPORT_LOCAL",
        "CONTROL_PLANE_TRANSPORT_FUTURE",
        "EXIT_OK",
        "EXIT_CONFIG_ERROR",
        "EXIT_PREFLIGHT_FAILURE",
        "EXIT_ALREADY_RUNNING",
        "EXIT_FATAL_RUNTIME_ERROR",
        "WorkerHostConfig",
        "PreflightCheck",
        "WorkerPreflightResult",
        "SingleInstanceLock",
        "configure_worker_logging",
        "redact_config",
        "run_capability_preflight",
        "WindowsWorkerHost",
        "HostStartResult",
        "windows_worker_main",
        "PRODUCTION_HANDLER_REGISTRY_VERSION",
        "build_production_handler_registry",
    }
)


def __getattr__(name: str):
    if name in _WINDOWS_WORKER_EXPORTS:
        from . import windows_worker as _ww

        if name == "windows_worker_main":
            return _ww.main
        return getattr(_ww, name)
    if name in _CONTROL_PLANE_EXPORTS:
        from . import control_plane as _cp

        return getattr(_cp, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

__all__ = [
    # M6-01 Operations domain model
    "OPERATIONS_SCHEMA_VERSION",
    "OPERATIONS_POLICY_VERSION",
    "OPERATIONS_USER_VERSION",
    "DEFAULT_OPERATIONS_PATH",
    "AssetLifecycleState",
    "JobState",
    "JobStage",
    "PipelineRunStatus",
    "TriggerType",
    "TERMINAL_JOB_STATES",
    "LEASE_HELD_JOB_STATES",
    "VALID_CAPABILITIES",
    "is_terminal_job_state",
    "is_legal_asset_transition",
    "is_legal_job_transition",
    "normalize_identity_component",
    "normalize_input_fingerprint",
    "normalize_job_stage",
    "normalize_capability",
    "normalize_capabilities",
    "compute_job_id",
    "is_valid_job_id",
    "utc_now_iso",
    "parse_iso",
    "format_iso",
    "compute_backoff_seconds",
    "compute_next_retry_at",
    "new_lease_token",
    "EnqueueResult",
    "ClaimedJob",
    "OperationsValidationResult",
    # M6-01 Operations store
    "OperationsError",
    "OperationsSchemaError",
    "OperationsStateError",
    "OperationsIntegrityError",
    "StaleLeaseError",
    "DEFAULT_MAX_ATTEMPTS",
    "DEFAULT_LEASE_DURATION_SECONDS",
    "DEFAULT_WORKER_STALE_THRESHOLD_SECONDS",
    "create_operations_store",
    "open_operations_store",
    "register_asset",
    "get_asset",
    "get_asset_by_canonical_id",
    "transition_asset_lifecycle",
    "admin_requeue_asset_lifecycle",
    "create_pipeline_run",
    "complete_pipeline_run",
    "get_pipeline_run",
    "enqueue_job",
    "get_job",
    "list_jobs",
    "list_pending_jobs",
    "list_failed_jobs",
    "transition_job_state",
    "begin_attempt",
    "finish_attempt",
    "list_job_attempts",
    "cancel_job",
    "requeue_retryable_job",
    "set_job_lease",
    "clear_job_lease",
    "register_worker",
    "worker_heartbeat",
    "list_workers",
    "list_workers_with_status",
    "claim_next_job",
    "renew_job_lease",
    "start_claimed_job",
    "complete_job_success",
    "complete_job_retryable_failure",
    "complete_job_terminal_failure",
    "find_active_claim",
    "replay_started_job",
    "replay_completed_job",
    "recover_expired_leases",
    "is_worker_stale",
    "get_job_result",
    "list_events",
    "validate_operations_store",
    # M6-02 Worker runtime
    "RetryableJobError",
    "TerminalJobError",
    "HandlerResult",
    "WorkerRunResult",
    "WorkerRuntime",
    "StageHandler",
    # M6-03 Pipeline stage adapters
    "STAGES_POLICY_VERSION",
    "STAGE_EXECUTION_RESULT_SCHEMA_VERSION",
    "STATUS_EXECUTED",
    "STATUS_CACHE_HIT",
    "ArtifactDescriptor",
    "StageExecutionResult",
    "is_valid_sha256",
    "fingerprint_artifacts",
    "stage_output_fingerprint",
    "required_capabilities_for_stage",
    "StageAdapter",
    "DiscoverAdapter",
    "ArchiveAdapter",
    "MediaProcessAdapter",
    "KnowledgeExtractAdapter",
    "KnowledgeFinalizeAdapter",
    "StoreIngestAdapter",
    "build_stage_handler_registry",
    "validate_stage_execution_result",
    # M6-04 Automatic pipeline scheduler
    "SCHEDULER_POLICY_VERSION",
    "SCHEDULER_SCHEMA_VERSION",
    "SchedulerCycleResult",
    "PollSource",
    "Scheduler",
    "SchedulerError",
    "discovery_control_fingerprint",
    "poll_slot_fingerprint",
    "epoch_seconds",
    # M6-05 Observability + admin
    "HEALTH_HEALTHY",
    "HEALTH_RUNNING",
    "HEALTH_WAITING_FOR_WORKER",
    "HEALTH_WAITING_RETRY",
    "HEALTH_SUCCEEDED",
    "HEALTH_FAILED_TERMINAL",
    "HEALTH_CANCELLED",
    "HEALTH_STALLED",
    "HEALTH_INVARIANT_ERROR",
    "MANUAL_ATTENTION_HEALTH",
    "AssetPipelineStatus",
    "WorkerStatus",
    "OperationsSummary",
    "get_asset_pipeline_status",
    "list_asset_pipeline_statuses",
    "get_worker_status",
    "list_worker_statuses",
    "compute_operations_summary",
    "get_asset_timeline",
    "ADMIN_POLICY_VERSION",
    "RecoveryResult",
    "AdminRetryResult",
    "AdminCancelResult",
    "run_recovery_pass",
    "startup_recovery",
    "admin_retry_job",
    "admin_cancel_job",
    "admin_requeue_asset",
    # M6-06 Windows worker host
    "WORKER_HOST_CONFIG_VERSION",
    "WORKER_PREFLIGHT_RESULT_VERSION",
    "WORKER_HOST_POLICY_VERSION",
    "WINDOWS_PC_TARGET_CAPABILITIES",
    "CONTROL_PLANE_TRANSPORT_LOCAL",
    "CONTROL_PLANE_TRANSPORT_FUTURE",
    "EXIT_OK",
    "EXIT_CONFIG_ERROR",
    "EXIT_PREFLIGHT_FAILURE",
    "EXIT_ALREADY_RUNNING",
    "EXIT_FATAL_RUNTIME_ERROR",
    "WorkerHostConfig",
    "PreflightCheck",
    "WorkerPreflightResult",
    "SingleInstanceLock",
    "configure_worker_logging",
    "redact_config",
    "run_capability_preflight",
    "WindowsWorkerHost",
    "HostStartResult",
    "windows_worker_main",
    # M6-07 Transport abstraction
    "TransportError",
    "RemoteUnavailableError",
    "WorkerOperationsTransport",
    "LocalSQLiteWorkerTransport",
    # M6-07 HTTP transport
    "CONTROL_PLANE_API_VERSION",
    "ERROR_CODE_AUTH_FAILED",
    "ERROR_CODE_VALIDATION_ERROR",
    "ERROR_CODE_NO_JOB",
    "ERROR_CODE_STALE_LEASE",
    "ERROR_CODE_CONFLICT",
    "ERROR_CODE_NOT_FOUND",
    "ERROR_CODE_SERVER_UNAVAILABLE",
    "ERROR_CODE_INVARIANT_ERROR",
    "ApiError",
    "AuthenticationError",
    "claimed_job_to_dict",
    "claimed_job_from_dict",
    "redact_job_payload",
    "HttpWorkerTransport",
    # M6-07 NAS control plane
    "CONTROL_PLANE_CONFIG_VERSION",
    "CONTROL_PLANE_POLICY_VERSION",
    "WINDOWS_STAGE_ALLOWLIST",
    "NAS_STAGE_ALLOWLIST",
    "DEFAULT_AUTH_TOKEN_ENV",
    "ControlPlaneConfig",
    "ControlPlaneService",
    "run_control_plane",
    "build_nas_local_handlers",
]